### ISSUE TITLE
Persistent error in VS Code related to markdown file name

### ISSUE THREAD

**Issue by frunox** [dashbitco/nimble_publisher#19]
I have an app that works using nimble_publisher (current version).  I started with 1 markdown file.  No problems.  I added a second markdown file with an improperly formatted name and get this error in the VS Code terminal:
_(ArgumentError) cannot parse "2022-02-22_back" as date, reason: :invalid_format

Stacktrace:
  │ (elixir 1.12.3) lib/calendar/date.ex:362: Date.from_iso8601!/2
  │ (discuss 0.1.0) lib/discuss/blog/post.ex:8: Discuss.Blog.Post.build/3
  │ (nimble_publisher 0.1.2) lib/nimble_publisher.ex:45: anonymous fn/5 in NimblePublisher.__extract__/2
  │ (elixir 1.12.3) lib/enum.ex:2385: Enum."-reduce/3-lists^foldl/2-0-"/3
  │ (nimble_publisher 0.1.2) lib/nimble_publisher.ex:42: NimblePublisher.__extract__/2
  │ lib/discuss/blog/blog.ex:4: (module)_
Notice I had an underscore in the file name.
Steps:

1.   I corrected the file name, but the error message persists.
2.   I moved the file to an unrelated folder, but the error message persists.
3.   I shut down the server and re-started it, but the error message persists.
4.   I restarted by computer, but the error message persists.
5.   I put the file back into the correct folder, and the error message persists.

My app works as expected - both markdown files are being rendered as expected using _Blog.all_posts()_ and _Blog.get_post_by_id!(id))_.  But, the error message is still showing in the VS Code terminal.

VS Code is highlighting this line in _blog.ex_:
` use NimblePublisher,`

This is an annoyance, so not critical, but the error message should be resolved after the file name was changed.

**Comment by josevalim** [comment]
I believe this was an Elixir bug. Can you try out Elixir v1.13?

**Comment by frunox** [comment]
The Windows installer isn't working.  It can't download the elixir.csv file.  I will continue trying.   Thanks for the quick response.

**Comment by josevalim** [comment]
Does this error persist? :)

**Comment by josevalim** [comment]
Closing this for now. Pls let us know if it persists!
