### ISSUE TITLE
Supporting additional programming languages

### ISSUE THREAD

**Issue by pepicrft** [dashbitco/nimble_publisher#20]
Hi,
First of all, thanks a lot for building this package. I'm using it in a personal web and it works incredibly well.
The one need I came across and I'm trying to find an answer is having code highlighters formatting programming languages other than the default ones (e.g., Ruby or Typescript). It's a bit confusing to me if the answer is that I have to implement my lexer, like [this HTML one](https://github.com/elixir-makeup/makeup_html), or it's something that can be generated from elsewhere.
Apologies if this issue doesn't fit this repository, but the little activity in the `makeup` repository makes it impossible for [this issue](https://github.com/elixir-makeup/makeup/issues/52) to have some visibility.
Once I better understand the problem I'll happily contribute to document/automate the process for people coming across the same need in the future.

**Comment by josevalim** [comment]
You will have to figure out what is wrong with makeup. We are just users of it, we don't know how to tackle your problem. Sorry!
