### ISSUE TITLE
Custom parser not being called on v1.0.2

### ISSUE THREAD

**Issue by thdaraujo** [dashbitco/nimble_publisher#21]
Hey, there!

Looks like version `v1.0.2` doesn't include the code from #16. Would it be possible to release a new version?

I was trying to use a custom parser, but it's currently only available on the master branch:
```
      # {:nimble_publisher, "~> 0.1.2"} # -> custom parser is not called
      {:nimble_publisher, github: "dashbitco/nimble_publisher", branch: "master"} # -> custom parser is called
```

Thanks!

**Comment by LostKobrakai** [comment]
I just bumped into the same issue. It can be seen here https://diff.hex.pm/diff/nimble_publisher/0.1.1..0.1.2, where the changes for custom parsers are missing.

**Comment by josevalim** [comment]
0.1.3 out

**Comment by thdaraujo** [comment]
thank you! 🙏
