### ISSUE TITLE
How to make avoid rebulding a whole project when *.md file gets changed? 

### ISSUE THREAD

**Issue by ponteshu** [dashbitco/nimble_publisher#22]
The library creates a module attribute which contains the content of all the files, which then gets embedded into the code of an application When used in production, any tiny change in any of those files -- `posts/*.md` -- then requires **rebuilding** of the whole application. The same goes for adding a new file.

I want it to be more dynamic **in production** as well. Yet, I don't want to bring in a database.

Is there a way to make it more dynamic? Namely, a change of `.md` file, or creating a new one, no longer require rebuilding the project. Restarting it will be fine, although preferably, I want to avoid it too. 

Make a change in a `md` file -- see it on a html page nearly immediately.

**Comment by josevalim** [comment]
Hi @ponteshu. This library has limited scope: it is meant to read files at compilation time and publish them. It is meant to be used as a simple blogging engine where you do deploy every time there is a new article.

I understand you have other needs but I am afraid you will need another library to achieve that. You can use some of the code here as a starting point though. Good luck!

**Comment by ponteshu** [comment]
I know what the library IS. But I've asked "Is there a way to **make it** more dynamic?"
