### ISSUE TITLE
Docs Incorrect?

### ISSUE THREAD

**Issue by jshekhawat** [dashbitco/nimble_publisher#31]
Hi,

Just checking if the documentation w.r.t HTMLConverter is correct or not. Currently, the first argument matches on extension name,
```elixir
defmodule MarkdownConverter do
  def convert(extname, body, _attrs, opts) when extname in [".md", ".markdown"] do
    highlighters = Keyword.get(opts, :highlighters, [])
    body |> Md.generate() |> NimblePublisher.highlight(highlighters)
  end
end
```

However, the first arg being passed is the filepath which will lead to an error being thrown for no function clause matching. Happy to raise a PR for the correction if it needs to be updated.

Thanks.

**Comment by josevalim** [comment]
Yes, we changed this before release and it seems we forgot to update some docs. PRs are welcome!
